title: "elementary Blog"
description: "We design and develop the fast, open, and privacy-respecting replacement for Windows and macOS"
organization: elementary, Inc
logo:
  image: svg/logomark.svg
  url: https://elementary.io
  svg: true # If true, it'll look for the specified SVG file in _includes
permalink: /:title/
theme-color: "#64baff"
gravatar: eaa3cc978770998ea2bd4382935bf0f4

social:
  rss: true
  facebook: elementaryos
  mastodon: elementary
  reddit_sub: elementaryos
  reddit_user: null
  stackexchange: elementaryos
  twitter: elementary
  slack: elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc
  # github: elementary
  # patreon: elementary
  # paypal: elementary

primary_navigation:
- title: Support
  url: https://elementary.io/support
- title: Developer
  url: https://developer.elementary.io
- title: Get Involved
  url: https://elementary.io/get-involved
- title: Store
  url: https://elementary.io/store/
- title: Blog
  url: /

secondary_navigation:
- title: OS Updates
  url: /tags/#updates
- title: Appcenter
  url: /tags/#appcenter
- title: Developers
  url: /tags/#devs
- title: Design
  url: /tags/#design

footer:
  - title: Press
    url: https://elementary.io/press
  - title: Brand
    url: https://elementary.io/brand
  - title: OEMs
    url: https://elementary.io/oem
  - title: Privacy
    url: https://elementary.io/privacy
  - title: Team
    url: https://elementary.io/team
  - title: Open Source
    url: https://elementary.io/open-source

authors:
  aroman:
    name: "Avi Romanoff"
    description: "Enthusiasm Evangelist"
  cassidyjames:
    name: Cassidy James Blaede
    description: "Co-founder & CXO"
    gravatar: 41275ecc8271aca852ce2c0ff72d2610 # Gravatar md5 hash
  danrabbit:
    name: Daniel Foré
    description: "Founder & CEO"
    gravatar: 1f3cc76b99b5d0dae8381a23f52ea96d
  karensophia:
    name: Karen Sophia
    description: "Customer Engagement"
    # gravatar: e0ac5d5e717da67a36ac72adf235bc42
  kgrubb:
    name: Keli Grubb
    description: Developer
    gravatar: 8e8d16d136c38f3a28820490c17928d1
  peteruithoven:
    name: Peter Uithoven
    description: "Front-end Developer"
    gravatar: f39b1485b28be1dc2b98f269235218bc
  anonymous:
    name: "Unknown Author"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
